### ISSUE TITLE
Disabling plugin terminates OpenCPN

### ISSUE THREAD

**Issue by marcobergman** [seandepagnier/autopilot_route_pi#19]
Both 0.5 on Raspbian, and 0.4.1.0 on Windows.

Side note: When I go test this plugin at the boat, I'd like to be able to revert to the stock OpenCPN route facility. To have to restart OpenCPN and possibly have lost track and route data is a bit too involved.

**Comment by seandepagnier** [comment]
I fixed in git.

**Comment by marcobergman** [comment]
It seems to be a bit better, however I can still make opencpn crash by subsequently enabling and disabling the plugin, activating and deactivating a random route in between. Takes only a few cycles. This is on raspbian 10 buster with opencpn 5.2.4. I pulled from git and compiled it on ubuntu today, there it did crash upon disabling as the original report. 

I have tried enabling and disabling without activating a route and then it does not crash.

**Comment by marcobergman** [comment]
Still happens under windows, the version 0.4.7.0 that was published in the beta plugin manager catalog. It happens upon clicking the OK button in the Options screen, after the autopilot_route plugin enabled checkbox was unchecked. This happens both then there is a route active and when no route is active. 

Disabling the plugin is important because in this phase, one might want to fall back to the OpenCPN stock route facility. With OpenCPN crashing, testing on the water becomes less inviting.

> 13:47:38.187 MESSAGE pluginmanager.cpp:1811 PlugInManager: Deactivating PlugIn: C:\Users\Marco Bergman\AppData\Local\opencpn\plugins\autopilot_route_pi.dll
> 13:47:39.507 MESSAGE s52plib.cpp:518 Core s52plib:  ppmm: 8.37209 rv_scale_factor: 0.637037  calc_display_size_mm: 344
> 13:47:39.507 MESSAGE chcanv.cpp:2376 Metrics:  m_display_size_mm: 344     g_Platform->getDisplaySize():  2880:1620   
> 13:47:39.507 MESSAGE chcanv.cpp:2381 wxDisplaySize(): 2880 1620
> 13:47:39.597 MESSAGE glChartCanvas.cpp:732 BuildFBO 3
> 13:47:39.597 MESSAGE glChartCanvas.cpp:1217 OpenGL Framebuffer OK, size = 2878
> 13:47:39.660 MESSAGE glChartCanvas.cpp:732 BuildFBO 3
> 13:47:39.660 MESSAGE glChartCanvas.cpp:1217 OpenGL Framebuffer OK, size = 2878
> 13:47:52.610 MESSAGE chart1.cpp:1853 
> 
> ________
> 
> 13:47:52.611    INFO logger.cpp:130 ------- OpenCPN version 5.6.2 restarted at 2022-07-08 -------
